service:
  name: wut-up-worl
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: dev
  region: us-east-1

include:
  - utils/**
exclude:
  - .gitignore
  - dist/**
  - LICENSE.md
  - node_modules/**
  - package.json
  - README.md
  - scripts/**
  - yarn.lock

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  getAllUsers:
    handler: src/api/User.getAllUsers
    events:
      - http:
          method: get
          path: users
  getUser:
    handler: src/api/User.getUser
    events:
      - http:
          method: get
          path: users/{id}
  createUser:
    handler: src/api/User.createUser
    events:
      - http:
          method: post
          path: users
  updateUser:
    handler: src/api/User.updateUser
    events:
      - http:
          method: patch
          path: users/{id}
  deleteUser:
    handler: src/api/User.deleteUser
    events:
      - http:
          method: delete
          path: users/{id}
